---
- hosts: all
  vars_files:
      - vars/icinga-vars.yml
      - vars/services.yml

  tasks:
     - name: Ensure that icinga repo exist
       apt_repository:
         repo=ppa:formorer/icinga
         state=present
       when: ansible_distribution == 'Ubuntu'

     - name: Ensure that pip / httplib2 / curl are installed
       apt:
         name={{ item }} state=present
       with_items:
         - python-pip
         - python-httplib2
         - curl

     - name: Install python requests
       pip:
         name=requests state=latest

<<<<<<< HEAD
     - name: Install python nagioscheck
       pip:
         name=nagioscheck state=latest
       when: "'Elastic' in group_names"

     - name: Install pymongo
       pip:
         name=pymongo state=latest
       when: "'Mongo' in group_names"

=======
>>>>>>> 6ee61338abb57dc32f7fb6cf4ef9d557106b43e5
     - name: Update apt cache if too old
       apt:
         update_cache=yes cache_valid_time=14400

     - name: Ensure nagios plugins package is installed
       apt:
         name=nagios-plugins state=present

     - name: Create Icinga2 host object through API
       uri:
          url=https://{{ icinga_ip }}:5665/v1/objects/hosts/{{ ansible_hostname }}
          method=PUT
          user={{ api_user }}
          password={{ api_pass }}
          headers={'Accept':'application/json'}
          body='{"templates":["generic-host"],"attrs":{"address":"{{ ansible_default_ipv4.address }}","check_command":"hostalive","vars.os":"Linux"}}'
          validate_certs={{ validate }}
          body_format=json
          status_code=200,500

<<<<<<< HEAD
     - include: tasks/generic-host.yml
       when: "'Linux' in group_names"

     - include: tasks/telegraf-host.yml
       when: "'Telegraf' in group_names"

     - include: tasks/mysql-host.yml
       when: "'Mysql' in group_names"

     - include: tasks/apache-host.yml
       when: "'Apache' in group_names"

     - include: tasks/nginx-host.yml
       when: "'Nginx' in group_names"

     - include: tasks/mongo-host.yml
       when: "'Mongo' in group_names"

     - include: tasks/elastic-host.yml
       when: "'Elastic' in group_names"

     - include: tasks/redis-host.yml
       when: "'Redis' in group_names"

     - include: tasks/haproxy-host.yml
       when: "'Haproxy' in group_names"

     - include: tasks/phpfpm-host.yml
       when: "'Php-fpm' in group_names"

     - include: tasks/hhvm-host.yml
       when: "'Hhvm' in group_names"

     - include: tasks/monit-host.yml
       when: "'Monit' in group_names"

     - include: tasks/memcached-host.yml
       when: "'Memcached' in group_names"
=======
     - name: Creating Icinga2 services for host {{ ansible_hostname }} through API
       uri:
          url=https://{{ icinga_ip }}:5665/v1/objects/services/{{ ansible_hostname }}!{{ item.name }}
          method=PUT
          user={{ api_user }}
          password={{ api_pass }}
          headers={'Accept':'application/json'}
          body='{"templates":["generic-service"],"attrs":{"display_name":"{{ item.name }}","check_command":"dummy","check_interval":"86400","vars.dummy_state":3,"vars.dummy_text":"No Passive Check Result Received"}}'
          validate_certs={{ validate }}
          body_format=json
          status_code=200,500
       with_items:
         - "{{ services }}"

     - name: Copy scripts for passive check results
       template:
          src=passive-result.py.j2
          dest={{ checks_path }}passive-{{ item.name }}-result.py
          mode=0755
          owner=root
          group=root
       with_items:
         - "{{ services }}"

     - name: Copy scripts for data collection
       copy:
          src={{ scripts_path }}{{ item.plugin }}
          dest={{ checks_path }}
          mode=0755
          owner=root
          group=root
       when: item.plugin is defined
       with_items:
         - "{{ services }}"
>>>>>>> 6ee61338abb57dc32f7fb6cf4ef9d557106b43e5
...
