---
- hosts: all
  vars_files:
      - vars/icinga-vars.yml
      - vars/services.yml

  tasks:
     - name: Include vars if host in Telegraf group
       include_vars: 
         dir=vars/influx
       when: "'Telegraf' in group_names"

     - name: Include vars if host in Apache group
       include_vars: 
         dir=vars/apache
       when: "'Apache' in group_names"

     - name: Include vars if host in Nginx group
       include_vars: 
         dir=vars/nginx
       when: "'Nginx' in group_names"

     - name: Include vars if host in Mysql group
       include_vars: 
         dir=vars/mysql
       when: "'Mysql' in group_names"

     - name: Include vars if host in Mongo group
       include_vars: 
         dir=vars/mongo
       when: "'Mongo' in group_names"

     - name: Include vars if host in Redis group
       include_vars: 
         dir=vars/redis
       when: "'Redis' in group_names"

     - name: Include vars if host in Elastic group
       include_vars: 
         dir=vars/elastic
       when: "'Elastic' in group_names"

     - name: Include vars if host in Haproxy group
       include_vars: 
         dir=vars/haproxy
       when: "'Haproxy' in group_names"

     - name: Include vars if host in Hhvm group
       include_vars: 
         dir=vars/hhvm
       when: "'Hhvm' in group_names"

     - name: Include vars if host in Monit group
       include_vars: 
         dir=vars/monit
       when: "'Monit' in group_names"

     - name: Include vars if host in Memcached group
       include_vars: 
         dir=vars/memcached
       when: "'Memcached' in group_names"

     - name: Include vars if host in Php-fpm group
       include_vars: 
         dir=vars/phpfpm
       when: "'Php-fpm' in group_names"

     - name: Ensure that icinga repo exist
       apt_repository:
         repo=ppa:formorer/icinga
         state=present
       when: ansible_distribution == 'Ubuntu'

     - name: Ensure that pip / httplib2 / curl are installed
       apt:
         name={{ item }} state=present
       with_items:
         - python-pip
         - python-httplib2
         - curl

     - name: Install python requests
       pip:
         name=requests state=latest

     - name: Install python nagioscheck
       pip:
         name=nagioscheck state=latest
       when: "'Elastic' in group_names"

     - name: Install pymongo
       pip:
         name=pymongo state=latest
       when: "'Mongo' in group_names"

     - name: Update apt cache if too old
       apt:
         update_cache=yes cache_valid_time=14400

     - name: Ensure nagios plugins package is installed
       apt:
         name=nagios-plugins state=present

     - name: Create Icinga2 host object through API
       uri:
          url=https://{{ icinga_ip }}:5665/v1/objects/hosts/{{ ansible_nodename }}
          method=PUT
          user={{ api_user }}
          password={{ api_pass }}
          headers={'Accept':'application/json'}
          body='{"templates":["generic-host"],"attrs":{"address":"{{ ansible_default_ipv4.address }}","check_command":"hostalive","vars.os":"Linux"}}'
          validate_certs={{ validate }}
          body_format=json
          status_code=200,500

     - include: tasks/generic-host.yml
       when: "'Linux' in group_names"

     - include: tasks/telegraf-host.yml
       when: "'Telegraf' in group_names"

     - include: tasks/mysql-host.yml
       when: "'Mysql' in group_names"

     - include: tasks/apache-host.yml
       when: "'Apache' in group_names"

     - include: tasks/nginx-host.yml
       when: "'Nginx' in group_names"

     - include: tasks/mongo-host.yml
       when: "'Mongo' in group_names"

     - include: tasks/elastic-host.yml
       when: "'Elastic' in group_names"

     - include: tasks/redis-host.yml
       when: "'Redis' in group_names"

     - include: tasks/haproxy-host.yml
       when: "'Haproxy' in group_names"

     - include: tasks/phpfpm-host.yml
       when: "'Php-fpm' in group_names"

     - include: tasks/hhvm-host.yml
       when: "'Hhvm' in group_names"

     - include: tasks/monit-host.yml
       when: "'Monit' in group_names"

     - include: tasks/memcached-host.yml
       when: "'Memcached' in group_names"
...
