---
- hosts: all

  tasks:
   - name: Show group_names
     debug:
        var=group_names

#   - name: save checks
#     shell: ls /usr/lib/nagios/plugins/ | grep check_
#     shell: service --status-all | grep + | awk -F"]" '{print $2}'
#     register: checks
#
#   - name: show services
#     debug:
#       var=checks.stdout_lines
#
   - name: Get redis ports
     shell: netstat -putan | grep redis | awk -F ':' '{print $2}' | cut -d" " -f 1 | uniq
     register: redis_port

   - debug:
       var: redis_port
