---
- hosts: all

  tasks:
   - name: Show group_names
     debug:
        var=group_names

#   - name: save checks
#     shell: ls /usr/lib/nagios/plugins/ | grep check_
#     shell: service --status-all | grep + | awk -F"]" '{print $2}'
#     register: checks
#
#   - name: show services
#     debug:
#       var=checks.stdout_lines
#
   - name: Get redis ports
#     shell: netstat -putan | grep redis | awk -F ':' '{print $2}' | cut -d" " -f 1 | uniq
     shell: netstat -putan | grep nginx | grep -Ev '^(tcp6)' | cut -d':' -f2 | cut -d' ' -f1 | uniq
     register: nginx_port

   - debug:
       var: nginx_port

   - local_action: copy content={{ nginx_port.stdout }} dest=./ports.txt
   - local_action: shell awk '$0="  - port{{':'}} "$0' ./ports.txt > ./nginxports.txt
   - local_action: lineinfile line=nginx{{':'}} insertbefore=BOF path=./nginxports.txt
