---
- name: Get haproxy port
  shell: grep -A 10 'frontend' /etc/haproxy/haproxy.cfg | grep bind | cut -d':' -f2
  register: haproxy_port

- name: Write ports to haproxy var file
  local_action: blockinfile block="{% for lines in haproxy_port.stdout_lines %}  - name{{':'}} haproxy-http-{{ lines }}\n    command{{':'}}\n      check_http -I {{ ansible_default_ipv4.address }} -p {{ lines }}\n{% endfor %}" insertafter="haproxy:" path=./vars/haproxy/haproxy.yml

- name: Creating Icinga2 haproxy service for host {{ ansible_nodename }} through API
  uri:
     url=https://{{ icinga_ip }}:5665/v1/objects/services/{{ ansible_nodename }}!{{ item.name }}
     method=PUT
     user={{ api_user }}
     password={{ api_pass }}
     headers={'Accept':'application/json'}
     body='{"templates":["generic-service"],"attrs":{"display_name":"{{ item.name }}","check_command":"dummy","check_interval":"86400","vars.dummy_state":3,"vars.dummy_text":"No Passive Check Result Received"}}'
     validate_certs={{ validate }}
     body_format=json
     status_code=200,500
  with_items:
    - "{{ haproxy }}"

- name: Copy script for haproxy passive check result
  template:
     src=passive-result.py.j2
     dest={{ checks_path }}passive-{{ item.name }}-result.py
     mode=0755
     owner=root
     group=root
  with_items:
    - "{{ haproxy }}"

- name: Copy script for haproxy data collection
  copy:
     src={{ scripts_path }}{{ item.plugin }}
     dest={{ checks_path }}
     mode=0755
     owner=root
     group=root
  when: item.plugin is defined
  with_items:
    - "{{ haproxy }}"

- name: Creating cron job for haproxy check
  cron:
     name="passive {{ item.name }} checks"
     job="{{ checks_path }}passive-{{ item.name }}-result.py"
     state=present
  with_items:
    - "{{ haproxy }}"
