---
- name: Get mongodb ports
  shell: netstat -putan | grep mongod | cut -d':' -f 2 | cut -d' ' -f1 | sort | uniq
  register: mongo_ports

- name: Write ports to mongo var file
  local_action: blockinfile block="{% for lines in mongo_ports.stdout_lines %}  - name{{':'}} mongod-{{ lines }}\n    command{{':'}}\n      check_mongodb.py -H {{ ansible_default_ipv4.address }} -P {{ lines }} -D\n    plugin:\n      check_mongodb.py\n{% endfor %}" insertafter="mongo:" path=./vars/mongo/mongo.yml

- name: Include mongo var files
  include_vars:
     dir=../vars/mongo

- name: Creating Icinga2 mongo service for host {{ ansible_nodename }} through API
  uri:
     url=https://{{ icinga_ip }}:5665/v1/objects/services/{{ ansible_nodename }}!{{ item.name }}
     method=PUT
     user={{ api_user }}
     password={{ api_pass }}
     headers={'Accept':'application/json'}
     body='{"templates":["generic-service"],"attrs":{"display_name":"{{ item.name }}","check_command":"dummy","check_interval":"86400","vars.dummy_state":3,"vars.dummy_text":"No Passive Check Result Received"}}'
     validate_certs={{ validate }}
     body_format=json
     status_code=200,500
  with_items:
    - "{{ mongo }}"

- name: Copy script for mongo passive check result
  template:
     src=passive-result.py.j2
     dest={{ checks_path }}passive-{{ item.name }}-result.py
     mode=0755
     owner=root
     group=root
  with_items:
    - "{{ mongo }}"

- name: Copy script for mongo data collection
  copy:
     src={{ scripts_path }}{{ item.plugin }}
     dest={{ checks_path }}
     mode=0755
     owner=root
     group=root
  when: item.plugin is defined
  with_items:
    - "{{ mongo }}"

- name: Creating cron job for mongo check
  cron:
     name="passive {{ item.name }} checks"
     job="{{ checks_path }}passive-{{ item.name }}-result.py"
     state=present
  with_items:
    - "{{ mongo }}"
