---
- name: Get nginx ports
  shell: netstat -putan | grep nginx | grep -Ev '^(tcp6)' | cut -d':' -f2 | cut -d' ' -f1 | uniq
  register: nginx_port

- name: Writing ports to nginx var file
  local_action: blockinfile block="{% for lines in nginx_port.stdout_lines %}  - name{{':'}} nginx-http-{{ lines }}\n    command{{':'}}\n      check_http -I {{ ansible_default_ipv4.address }} -p {{ lines }}\n{% endfor %}" insertafter="nginx.sh" path=./vars/nginx/nginx.yml

- name: Creating Icinga2 nginx service for host {{ ansible_nodename }} through API
  uri:
     url=https://{{ icinga_ip }}:5665/v1/objects/services/{{ ansible_nodename }}!{{ item.name }}
     method=PUT
     user={{ api_user }}
     password={{ api_pass }}
     headers={'Accept':'application/json'}
     body='{"templates":["generic-service"],"attrs":{"display_name":"{{ item.name }}","check_command":"dummy","check_interval":"86400","vars.dummy_state":3,"vars.dummy_text":"No Passive Check Result Received"}}'
     validate_certs={{ validate }}
     body_format=json
     status_code=200,500
  with_items:
    - "{{ nginx }}"

- name: Copy script for nginx passive check result
  template:
     src=passive-result.py.j2
     dest={{ checks_path }}passive-{{ item.name }}-result.py
     mode=0755
     owner=root
     group=root
  with_items:
    - "{{ nginx }}"

- name: Copy script for nginx data collection
  copy:
     src={{ scripts_path }}{{ item.plugin }}
     dest={{ checks_path }}
     mode=0755
     owner=root
     group=root
  when: item.plugin is defined
  with_items:
    - "{{ nginx }}"

- name: Creating cron job for nginx check
  cron:
     name="passive {{ item.name }} checks"
     job="{{ checks_path }}passive-{{ item.name }}-result.py"
     state=present
  with_items:
    - "{{ nginx }}"
