---
services:
  - name: apt
    command:
      check_apt
  - name: disk
    command:
      check_disk -w 30% -c 20%
  - name: telegraf-input
    command:
      telegraf-noinput.py -Q -i {{ influxdb_ip }} -d {{ influx_db }} -H {{ hostname }} -t {{ telegraf_time }}
    plugin:
      telegraf-noinput.py
...
